services:

  backend:
    image: sudharsanprakalathanvm/ammufoods-backend:${IMAGE_TAG}
    container_name: ammu-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  frontend:
    image: sudharsanprakalathanvm/ammufoods-frontend:${IMAGE_TAG}
    container_name: ammu-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped