apiVersion: apps/v1
kind: Deployment

metadata:
  name: ammufoods-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ammufoods-backend

  template:
    metadata:
      labels:
        app: ammufoods-backend

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"

    spec:
      containers:
      - name: backend

        image: sudharsanprakalathanvm/ammufoods-backend:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - secretRef:
            name: ammufoods-secret

        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 30
          periodSeconds: 15

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"