apiVersion: v1
kind: Service

metadata:
  name: ammufoods-backend-service

spec:
  selector:
    app: ammufoods-backend

  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

  type: ClusterIP